name: Zapakiraj in objavi Docker zabojnik
on:
  workflow_run:
    workflows: ["Testiranje kode"]
    types:
      - completed
    branches: [master]

jobs:
  docker-build-push:
    runs-on: self-hosted
    # Izvedi samo, če je bil prejšnji workflow uspešno zaključen
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Kloniranje repozitorija
        uses: actions/checkout@v4
      
      - name: Prijava v DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Ustvari Dockerfile, če ne obstaja
        run: |
          if [ ! -f Dockerfile ]; then
            echo "Dockerfile ne obstaja, ustvarjam privzetega..."
            cat > Dockerfile << EOF
            FROM gcc:latest
            
            WORKDIR /app
            
            COPY . .
            
            RUN gcc -o test_program main.c test_main.c
            
            CMD ["./test_program"]
            EOF
          fi

      - name: Zgradi docker sliko
        run: |
          echo "docker build"
          docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/cicd-projekt

      - name: Potisni docker sliko
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicd-projekt

      - name: Izpiši povezavo do objavljenega zabojnika
        run: |
          echo "Zabojnik uspešno objavljen na DockerHub:"
          echo "https://hub.docker.com/r/${{ secrets.DOCKERHUB_USERNAME }}/cicd-projekt"