name: Zapakiraj in objavi Docker zabojnik

on:
  workflow_run:
    workflows: ["Testiranje kode"]
    types:
      - completed
    branches: [master]

jobs:
  docker-build-push:
    runs-on: self-hosted
    # Izvedi samo, če je bil prejšnji workflow uspešno zaključen
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Kloniranje repozitorija
        uses: actions/checkout@v4
      
      - name: Nastavitev Docker pravic
        run: |
          sudo chmod 666 /var/run/docker.sock || true
          sudo systemctl restart docker || true
      
      - name: Prijava v DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Zgradi docker sliko
        run: |
          echo "Docker slika se gradi..."
          sudo docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/cicd-projekt:latest

      - name: Potisni docker sliko
        run: |
          sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicd-projekt:latest