name: Zapakiraj in objavi Docker zabojnik

on:
  workflow_run:
    workflows: ["Testiranje kode"]
    types:
      - completed
    branches: [master]

jobs:
  docker-build-push:
    runs-on: self-hosted
    # Izvedi samo, če je bil prejšnji workflow uspešno zaključen
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Kloniranje repozitorija
        uses: actions/checkout@v4
        
      - name: Potisni na docker hub z akcijo
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          registry: docker.io            
          dockerfile: Dockerfile
          tags: latest
          image: ${{secrets.DOCKERHUB_USERNAME}}/cicd-projekt