name: Zapakiraj in objavi Docker zabojnik

on:
  workflow_run:
    workflows: ["Testiranje kode"]
    types:
      - completed
    branches: [master]

jobs:
  docker-build-push:
    runs-on: self-hosted
    # Izvedi samo, če je bil prejšnji workflow uspešno zaključen
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Kloniranje repozitorija
        uses: actions/checkout@v4
      
      - name: Prijava v DockerHub
        uses: docker/login-action@v3
        with:
          username: "svenplib"
          password: "dckr_pat_pIhOUY-Gma5EB5XDNsSx7XGbpQs"

      - name: Zgradi docker sliko
        run: |
          echo "Docker slika se gradi..."
          sudo docker build . --file Dockerfile --tag svenplib/cicd-projekt:latest

      - name: Potisni docker sliko
        run: |
          sudo docker push svenplib/cicd-projekt:latest