name: TEST


env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
on:
  workflow_run:
    workflows: ["Testiranje kode"]
    types:
      - completed
    branches: [master]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    # Izvedi samo, če je bil prejšnji workflow uspešno zaključen
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Kloniranje repozitorija
        uses: actions/checkout@v4
      
      - name: Prijava v DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Zgradi docker sliko
        run: |
          echo "Docker slika se gradi..."
          docker build . --file Dockerfile --tag ${{ env.DOCKERHUB_USERNAME }}/cicd-projekt:latest
      - name: Potisni docker sliko
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/cicd-projekt:latest
